-- Add qr_theme to entity table
-- Stores a JSON object of CSS variable overrides generated by Grok AI
-- Example: { "primary": "#e63946", "bg": "#1a1a2e", "font": "'Georgia', serif" }
ALTER TABLE entity ADD COLUMN IF NOT EXISTS qr_theme JSONB;
